hanzanhae/Final_Project

src/components/MainHeader.jsx
src/redux/config/ThemeReducer.js
src/styles/mainPage/HeaderStyle.js

헤더테마변경 오류 수정
로그인 페이지 헤더색상 고정으로 수정

🎨: 테마스타일수정

---

src/components/detailPage/Detail.jsx
src/components/mainPage/section01/FilterKeyword.jsx
src/components/mainPage/section01/FilterMenu.jsx
src/components/mainPage/section01/MeetingList.jsx
src/meetingList.js
src/styles/mainPage/MeetingListStyle.js

메인페이지 섹션1
- 더보기페이지네이션 기능 임시구현
- 필터메뉴 수정 : 키워드 다중선택기능 추가
모임상세페이지
- 페이지이동 시 스크롤 상단고정

✨: 더보기페이지네이션기능추가

---

src/components/detailPage/DetailInfo.jsx
src/components/detailPage/DetailMember.jsx
src/components/mainPage/section01/MeetingList.jsx
src/redux/actions/themeActions.js
src/styles/detailPage/DetailStyle.js
src/styles/mainPage/MeetingListStyle.js

메인페이지
- 모임인원수 랜덤구현 & 스타일수정
모임 상세페이지
- 모임참가하기 버튼구현 & 10명제한

✨: 모임참가하기 기능구현

---

src/components/MainHeader.jsx
src/components/detailPage/MemberMenu.jsx
src/components/detailPage/ReportModal.jsx
src/data/meetingList.js

🛠:주석삭제&맴버모달창코드수정

---

src/components/button/UniBtn.jsx
src/components/detailPage/DetailMember.jsx
src/components/detailPage/ReportModal.jsx
src/components/mainPage/section01/FilterKeyword.jsx
src/styles/detailPage/DetailStyle.js
src/styles/mainPage/FilterMenuStyle.js

🎨​: 버튼컴포넌트 수정

---

src/api/api.js
src/components/mainPage/section01/MeetingList.jsx
src/data/meetingList.js

🛠: 메인페이지코드수정

---

package-lock.json
src/components/MainHeader.jsx
src/components/detailPage/DetailInfo.jsx
src/components/detailPage/DetailLocation.jsx
src/components/mainPage/section01/MeetingList.jsx
src/styles/detailPage/DetailStyle.js

모임상세페이지 카카오맵연결 >> 현재 사용자위치로 임시지정

✨: 모임상세페이지 카카오맵연결

---

package-lock.json
src/api/api.js
src/components/CreateRoom/CreateMeetingFormStyled.js
src/components/detailPage/Detail.jsx
src/components/detailPage/DetailLocation.jsx
src/components/mainPage/section01/MeetingList.jsx
src/shared/Router.js

🛠: api코드수정

---

src/components/CreateRoom/CreateMeetingFormStyled.js
src/components/mainPage/Banner.jsx
src/styles/theme.js

배너
- 모임개설버튼 스타일 수정
- 배경이미지에 필터테마 적용
모임개설페이지
- 배경이미지에 필터테마 적용

🎨​: 테마스타일추가

---

src/components/button/UniBtn.jsx
src/components/detailPage/DetailMember.jsx
src/components/mainPage/section01/FilterKeywordMenuLists.jsx
src/components/mainPage/section01/FilterMenu.jsx
src/components/mainPage/section01/FilterMyLocation.jsx
src/styles/theme.js

🎨: '내주변모임'버튼추가

---

package-lock.json
package.json
src/api/api.js
src/components/detailPage/Detail.jsx
src/components/detailPage/DetailInfo.jsx
src/components/detailPage/DetailMember.jsx
src/components/detailPage/InfoLocation.jsx
src/components/detailPage/InfoScript.jsx
src/components/detailPage/InfoTime.jsx
src/components/detailPage/MembersBox.jsx
src/components/mainPage/section01/ListBoxKeyword.jsx
src/components/mainPage/section01/ListBoxMembers.jsx
src/components/mainPage/section01/ListBoxTime.jsx
src/components/mainPage/section01/MeetingList.jsx
src/components/mainPage/section01/MeetingListBox.jsx
src/components/mypage/EventRequestForm.jsx

메인페이지 모임목록 서버연결완료
모임목록 id에 따른 상세페이지 연결완료

✨: 모임목록서버연결

---

src/components/detailPage/InfoScript.jsx
src/components/mainPage/section01/FilterKeywordMenuLists.jsx
src/components/mainPage/section01/ListBoxKeyword.jsx
src/components/mainPage/section01/ListBoxMembers.jsx
src/components/mainPage/section01/ListBoxTime.jsx
src/components/mainPage/section01/MeetingList.jsx
src/components/mainPage/section01/MeetingListBox.jsx
src/data/gatheringKeyword.js
src/data/meetingList.js

메인페이지 '참여불가' 필터메뉴 추가
필터링코드 전체 수정

✨:참여불가필터추가&필터코드수정

---

src/api/api.js
src/api/instance.js
src/components/detailPage/Detail.jsx
src/components/detailPage/DetailMember.jsx
src/components/detailPage/MembersBox.jsx
src/components/mainPage/section01/MeetingList.jsx
src/components/mainPage/section01/MeetingListBox.jsx

모임상세페이지 유저이름클릭 >> 메뉴나오게연결(채팅하기, 신고하기)

✨:모임상세페이지 유저클릭메뉴연결

---

src/api/api.js
src/api/instance.js
src/components/detailPage/Detail.jsx
src/components/detailPage/DetailMember.jsx
src/components/detailPage/InfoLocation.jsx
src/components/detailPage/InfoScript.jsx
src/components/detailPage/InfoTime.jsx

모임상세페이지
- api수정(연결미완료)
- 모임참가여부텍스트 추가

✨:모임참가여부기능추가&🛠:상세페이지api수정

---

src/components/header/HeaderWeather.jsx

날씨테마변경코드에서 사용자위치를 가져오는 부분을 커스텀훅을 사용했습니다.

♻️: 날씨코드커스텀훅사용

---

src/api/api.js
src/components/detailPage/DetailMember.jsx
src/components/detailPage/MembersBox.jsx
src/components/mainPage/section01/ListBoxMembers.jsx

🐛: slice오류해결

---

src/api/api.js
src/components/detailPage/DetailMember.jsx
src/components/mainPage/section01/ListBoxMembers.jsx
src/components/mainPage/section01/MeetingList.jsx

✨:모임참가기능추가

---

src/api/api.js
src/components/mainPage/section01/MeetingList.jsx

🐛: 페이지네이션오류수정

---

src/api/api.js
src/components/mainPage/section01/MeetingListBox.jsx

메인페이지
- 모임등록여부 확인완료
- 등록된 이미지 연결완료

✨:모임등록완료&등록이미지연결완료

---

src/components/detailPage/Detail.jsx
src/components/detailPage/DetailMember.jsx
src/components/detailPage/InfoLocation.jsx
src/components/detailPage/InfoScript.jsx
src/components/detailPage/InfoTime.jsx
src/components/detailPage/MembersBox.jsx
src/components/mainPage/section01/MeetingList.jsx
src/components/mainPage/section01/MeetingListBox.jsx
src/shared/Router.js

🐛: 모임상세페이지 연결오류해결

---

src/api/api.js
src/components/detailPage/Detail.jsx
src/components/detailPage/DetailLocation.jsx
src/components/detailPage/DetailMember.jsx
src/components/detailPage/InfoLocation.jsx
src/components/detailPage/MemberMenu.jsx
src/components/detailPage/MembersBox.jsx
src/components/mainPage/section01/ListBoxMembers.jsx
src/components/mainPage/section01/MeetingListBox.jsx

모임상세페이지
- 모임참가 시 렌더링오류해결
- 참가취소방법수정 >> 구성원클릭 시 참가해제되도록 변경
- 등록위치 위도,경도값 받아와서 상세페이지 지도연결 완료

🐛:모임참가오류수정&✨:등록모임위치연결완료

---

src/api/api.js
src/components/mainPage/Section01.jsx
src/components/mainPage/section01/FilterMenu.jsx
src/components/mainPage/section01/FilterMyLocation.jsx
src/components/mainPage/section01/ListBoxMembers.jsx
src/components/mainPage/section01/MeetingList.jsx
src/hooks/useLocationAddress.jsx

✨: 위치기반모임조회api연결완료

---

src/components/detailPage/DetailMember.jsx
src/components/mainPage/Section01.jsx
src/components/mainPage/section01/FilterKeyword.jsx
src/components/mainPage/section01/FilterMenu.jsx

✨:사용자위치필터링해제기능추가

---

src/components/chat/Chat.jsx
src/components/chat/ChatContainer.jsx
src/components/chat/ExampleChat.jsx
src/components/chat/chatLayout/ChatLayout.jsx
src/components/chat/chatLayout/ChatRoomListLayout.jsx
src/components/chat/chatRoom/ChatRoom.jsx

웹소켓 통신관련 연결완료
웹소켓 서버에서 온 메세지 수신완료

✨ Feat : 웹소켓 통신완료

---

package-lock.json
src/components/CreateRoom/CreateMeeting.jsx
src/components/CreateRoom/CreateRoom.jsx
src/components/mainPage/MainMap.jsx
src/components/mainPage/MainMapStyled.js

이미지 등록 안 해도 모임 개설 할 수 있게 수정 했습니다
메인 지도에서 마커 클릭시 해당하는 디테일 페이지로 이동하게 구현 했습니다

🛠 ​ Chore: 메인페이지 수정 및 이미지 미 등록 모임 개설

---

src/components/CreateRoom/CreateMeeting.jsx
src/components/CreateRoom/CreateMeetingFormStyled.js

모임 개설 페이지의 모든 필수 입력 값에 대한 유효성 검사를 완료했습니다

🛠 ​ Chore:모임 개설 페이지 유효성 검사 완료

---

package-lock.json
package.json
src/App.js
src/api/api.js
src/components/chat/Chat.jsx
src/components/chat/ChatContainer.jsx
src/components/chat/chatLayout/ChatRoomListLayout.jsx
src/components/chat/chatRoom/ChatRoom.jsx
src/components/detailPage/Detail.jsx
src/components/detailPage/DetailMember.jsx
src/components/detailPage/MemberMenu.jsx
src/components/detailPage/MembersBox.jsx
src/components/header/HeaderMenu.jsx
src/components/header/MainHeader.jsx
src/components/login/LoginForm.jsx
src/pages/DetailMeeting.jsx
src/pages/Home.jsx

1:1 채팅기능 수정
채팅 컴포넌트 수정
채팅 API 수정

🛠 Fix : 웹소켓 유저간 통신 기능 수정

---

src/api/api.js
src/components/chat/chatLayout/ChatLayout.jsx
src/components/chat/chatLayout/ChatRoomListLayout.jsx
src/components/chat/chatRoom/ChatRoom.jsx
src/components/header/HeaderMenu.jsx
src/redux/reducers/unreadMessagesReducer.js
src/redux/store/store.js

채팅기능 구현 완료 ( 1:1) 만
알림 기능 구현 ( 절반 )

✨ Feat : 채팅기능 구현 완료 및 알림 기능 구현

---

src/components/CreateRoom/CreateMeeting.jsx
src/components/CreateRoom/CreateMeetingFormStyled.js
src/components/mainPage/section01/MeetingList.jsx

🎨:모임등록페이지스타일수정

---

src/components/detailPage/MembersBox.jsx

🛠​유저닉네임코드수정

---

src/api/api.js
src/components/CreateRoom/CreateMeeting.jsx
src/components/calendar/Calendar.jsx
src/components/calendar/Days.jsx
src/components/calendar/DaysGrid.jsx
src/components/chat/chatLayout/ChatLayout.jsx
src/components/chat/chatLayout/ChatRoomListLayout.jsx
src/components/detailPage/DetailMember.jsx
src/components/login/LoginForm.jsx
src/pages/Home.jsx

🛠 Feat : 그룹채팅 생성 및 참여 기능 수정

---

src/api/api.js
src/components/CreateRoom/CreateMeeting.jsx
src/components/calendar/Calendar.jsx
src/components/calendar/Days.jsx
src/components/calendar/DaysGrid.jsx
src/components/chat/chatLayout/ChatLayout.jsx
src/components/chat/chatLayout/ChatRoomListLayout.jsx
src/components/detailPage/DetailMember.jsx
src/components/detailPage/MembersBox.jsx
src/components/login/LoginForm.jsx
src/pages/Home.jsx

🛠 Fix : 채팅기능 전체 수정 후 Merge

---

src/api/api.js
src/components/chat/Chat.jsx
src/components/chat/chatLayout/ChatRoomListLayout.jsx
src/components/chat/chatRoom/ChatRoom.jsx
src/components/detailPage/DetailMember.jsx
src/components/detailPage/MemberMenu.jsx
src/components/header/HeaderWeather.jsx
src/components/login/LoginForm.jsx
src/components/mainPage/KakaoMapSearch.jsx
src/components/mainPage/MainMap.jsx
src/components/mainPage/MainMapStyled.js
src/pages/ChatChat.jsx
src/pages/Home.jsx
src/shared/Router.js

카카오유저 채팅기능 구현완료
채팅유저 프로필 이미지 없을 시 기본이미지 부여
모임 마커 검색기능 구현
마커 클릭시 카카오지도 이동기능 구현

🛠 Fix : 카카오유저 채팅기능 구현완료

---

src/api/api.js
src/components/calendar/Calendar.jsx
src/components/calendar/CumulationCount.jsx
src/components/calendar/DateModal.jsx
src/components/calendar/Days.jsx
src/components/calendar/DaysGrid.jsx
src/components/calendar/JoinCount.jsx
src/components/mypage/CompleteModal.jsx
src/components/mypage/MyMeetings.jsx
src/pages/Home.jsx

런닝완료 시 캘린더와 연동 기능 구현
캘린더부분 해당 날짜 클릭시 있었던 런닝모임 모달창 구현

✨ Feat : 런닝완료 시 캘린더와 연동 기능 구현
